<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

define( 'WEBSQUAD_COOKIES_TEXT_DOMAIN', 'websquad-cookies' );

class WebSquadCookiesSettings {
	private $websquad_cookies_settings_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'websquad_cookies_settings_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'websquad_cookies_settings_page_init' ) );
	}

	public function websquad_cookies_settings_add_plugin_page() {
		add_menu_page(
			'Switch - Simple Cookie Notice Settings', // page_title
			'Cookie Notice', // menu_title
			'manage_options', // capability
			'websquad-cookies-settings', // menu_slug
			array( $this, 'websquad_cookies_settings_create_admin_page' ), // function
			'dashicons-palmtree',
            // plugins_url( 'switch-simple-cookie-notice/icon.png' ), // icon_url
			80 // position
		);
	}

	public function websquad_cookies_settings_create_admin_page() {
		$this->websquad_cookies_settings_options = get_option( 'websquad_cookies_settings_option_name' ); ?>

		<div class="wrap">
			<h2>Switch - Simple Cookie Notice Settings</h2>
			<p>Settings for Switch - Simple Cookie Notice</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'websquad_cookies_settings_option_group' );
					do_settings_sections( 'websquad-cookies-settings-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function websquad_cookies_settings_page_init() {
		register_setting(
			'websquad_cookies_settings_option_group', // option_group
			'websquad_cookies_settings_option_name', // option_name
			array( $this, 'websquad_cookies_settings_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'websquad_cookies_settings_setting_section', // id
			'Settings', // title
			array( $this, 'websquad_cookies_settings_section_info' ), // callback
			'websquad-cookies-settings-admin' // page
		);

		add_settings_field(
			'cookie_text_0', // id
			'Cookie text', // title
			array( $this, 'cookie_text_0_callback' ), // callback
			'websquad-cookies-settings-admin', // page
			'websquad_cookies_settings_setting_section' // section
		);

		add_settings_field(
			'button_text_1', // id
			'Button text', // title
			array( $this, 'button_text_1_callback' ), // callback
			'websquad-cookies-settings-admin', // page
			'websquad_cookies_settings_setting_section' // section
		);

		add_settings_field(
			'button_classes_2', // id
			'Button classes', // title
			array( $this, 'button_classes_2_callback' ), // callback
			'websquad-cookies-settings-admin', // page
			'websquad_cookies_settings_setting_section' // section
		);
		
		add_settings_field(
			'button_text_3', // id
			'Optional button text', // title
			array( $this, 'button_text_3_callback' ), // callback
			'websquad-cookies-settings-admin', // page
			'websquad_cookies_settings_setting_section' // section
		);
		
		add_settings_field(
			'button_classes_4', // id
			'Optional button classes', // title
			array( $this, 'button_classes_4_callback' ), // callback
			'websquad-cookies-settings-admin', // page
			'websquad_cookies_settings_setting_section' // section
		);

		add_settings_field(
			'button_url_5', // id
			'Optional button link', // title
			array( $this, 'button_url_5_callback' ), // callback
			'websquad-cookies-settings-admin', // page
			'websquad_cookies_settings_setting_section' // section
		);
	}

	public function websquad_cookies_settings_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['cookie_text_0'] ) ) {
			$sanitary_values['cookie_text_0'] = esc_textarea( $input['cookie_text_0'] );
			$sanitary_values['cookie_text_0'] = $input['cookie_text_0'];

			if (defined('ICL_SITEPRESS_VERSION')) {
				// Store the value in WPML String Translation
				icl_register_string( WEBSQUAD_COOKIES_TEXT_DOMAIN, 'Cookie Text 0', $sanitary_values['cookie_text_0'] );
			}
		}

		if ( isset( $input['button_text_1'] ) ) {
			$sanitary_values['button_text_1'] = sanitize_text_field( $input['button_text_1'] );

			if (defined('ICL_SITEPRESS_VERSION')) {
				// Store the value in WPML String Translation
				icl_register_string( WEBSQUAD_COOKIES_TEXT_DOMAIN, 'Button Text 1', $sanitary_values['button_text_1'] );
			}
		}

		if ( isset( $input['button_classes_2'] ) ) {
			$sanitary_values['button_classes_2'] = sanitize_text_field( $input['button_classes_2'] );
		}

		if ( isset( $input['button_text_3'] ) ) {
			$sanitary_values['button_text_3'] = sanitize_text_field( $input['button_text_3'] );

			if (defined('ICL_SITEPRESS_VERSION')) {
				// Store the value in WPML String Translation
				icl_register_string( WEBSQUAD_COOKIES_TEXT_DOMAIN, 'Button Text 3', $sanitary_values['button_text_3'] );
			}
		}

		if ( isset( $input['button_classes_4'] ) ) {
			$sanitary_values['button_classes_4'] = sanitize_text_field( $input['button_classes_4'] );
		}
		if ( isset( $input['button_url_5'] ) ) {
			$sanitary_values['button_url_5'] = esc_url_raw( $input['button_url_5'] );
		}

		return $sanitary_values;
	}

	public function websquad_cookies_settings_section_info() {
		
	}

	public function cookie_text_0_callback() {
		if (defined('ICL_SITEPRESS_VERSION')) {
			$translated_value = icl_t( WEBSQUAD_COOKIES_TEXT_DOMAIN, 'Cookie Text 0', $this->websquad_cookies_settings_options['cookie_text_0'] );
		} else {
			$translated_value = isset( $this->websquad_cookies_settings_options['cookie_text_0'] ) ? esc_attr( $this->websquad_cookies_settings_options['cookie_text_0']) : '';
		}

		printf(
			'<textarea class="large-text" rows="5" name="websquad_cookies_settings_option_name[cookie_text_0]" id="cookie_text_0">%s</textarea>',
			$translated_value
		);
	}

	public function button_text_1_callback() {
		if (defined('ICL_SITEPRESS_VERSION')) {
			$translated_value = icl_t( WEBSQUAD_COOKIES_TEXT_DOMAIN, 'Button Text 1', $this->websquad_cookies_settings_options['button_text_1'] );
		} else {
			$translated_value = isset( $this->websquad_cookies_settings_options['button_text_1'] ) ? esc_attr( $this->websquad_cookies_settings_options['button_text_1']) : '';
		}

		printf(
			'<input class="regular-text" type="text" name="websquad_cookies_settings_option_name[button_text_1]" id="button_text_1" value="%s">',
			$translated_value
		);
	}

	public function button_classes_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="websquad_cookies_settings_option_name[button_classes_2]" id="button_classes_2" value="%s">',
			isset( $this->websquad_cookies_settings_options['button_classes_2'] ) ? esc_attr( $this->websquad_cookies_settings_options['button_classes_2']) : ''
		);
	}

	public function button_text_3_callback() {
		if (defined('ICL_SITEPRESS_VERSION')) {
			$translated_value = icl_t( WEBSQUAD_COOKIES_TEXT_DOMAIN, 'Button Text 3', $this->websquad_cookies_settings_options['button_text_3'] );
		} else {
			$translated_value = isset( $this->websquad_cookies_settings_options['button_text_3'] ) ? esc_attr( $this->websquad_cookies_settings_options['button_text_3']) : '';
		}
		
		printf(
			'<input class="regular-text" type="text" name="websquad_cookies_settings_option_name[button_text_3]" id="button_text_3" value="%s">',
			$translated_value
		);
	}

	public function button_classes_4_callback() {
		printf(
			'<input class="regular-text" type="text" name="websquad_cookies_settings_option_name[button_classes_4]" id="button_classes_4" value="%s">',
			isset( $this->websquad_cookies_settings_options['button_classes_4'] ) ? esc_attr( $this->websquad_cookies_settings_options['button_classes_4']) : ''
		);
	}

	public function button_url_5_callback() {
		printf(
			'<input class="regular-text" type="text" name="websquad_cookies_settings_option_name[button_url_5]" id="button_url_5" value="%s">',
			isset( $this->websquad_cookies_settings_options['button_url_5'] ) ? esc_attr( $this->websquad_cookies_settings_options['button_url_5']) : ''
		);
	}

}
if ( is_admin() )
	$websquad_cookies_settings = new WebSquadCookiesSettings();

/* 
 * Retrieve this value with:
 * $websquad_cookies_settings_options = get_option( 'websquad_cookies_settings_option_name' ); // Array of All Options
 * $cookie_text_0 = $websquad_cookies_settings_options['cookie_text_0']; // Cookie text
 * $button_text_1 = $websquad_cookies_settings_options['button_text_1']; // Button text
 * $button_classes_2 = $websquad_cookies_settings_options['button_classes_2']; // Button classes
 * $button_text_3 = $websquad_cookies_settings_options['button_text_3']; // Button text
 * $button_classes_4 = $websquad_cookies_settings_options['button_classes_4']; // Button classes
 */
